spring.application.name=demo2
server.port=9000

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=varun
spring.datasource.password=2006

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
